#==============================================================================
#   WARNING!!  This file is overwritten by the Block UI Styler while generating
#   the automation code. Any modifications to this file will be lost after
#   generating the code again.
# 
#        Filename:  D:\Projects\github-nx-macros\test8-components\dialog.py
# 
#         This file was generated by the NX Block UI Styler
#         Created by: nikita
#               Version: NX 12
#               Date: 06-09-2025  (Format: mm-dd-yyyy)
#               Time: 17:35 (Format: hh-mm)
# 
#==============================================================================

#==============================================================================
#   Purpose:  This TEMPLATE file contains Python source to guide you in the
#   construction of your Block application dialog. The generation of your
#   dialog file (.dlx extension) is the first step towards dialog construction
#   within NX.  You must now create a NX Open application that
#   utilizes this file (.dlx).
# 
#   The information in this file provides you with the following:
# 
#   1.  Help on how to load and display your Block UI Styler dialog in NX
#       using APIs provided in NXOpen.BlockStyler namespace
#   2.  The empty callback methods (stubs) associated with your dialog items
#       have also been placed in this file. These empty methods have been
#       created simply to start you along with your coding requirements.
#       The method name, argument list and possible return values have already
#       been provided for you.
#==============================================================================

#------------------------------------------------------------------------------
# These imports are needed for the following template code
#------------------------------------------------------------------------------
import NXOpen
import NXOpen.BlockStyler

#------------------------------------------------------------------------------
# Represents Block Styler application cls
#------------------------------------------------------------------------------
class dialog:
    # static class members
    theSession = None
    theUI = None
    
    #------------------------------------------------------------------------------
    # Constructor for NX Styler class
    #------------------------------------------------------------------------------
    def __init__(self):
        try:
            self.theSession = NXOpen.Session.GetSession()
            self.theUI = NXOpen.UI.GetUI()
            self.theDlxFileName = "dialog.dlx"
            self.theDialog = self.theUI.CreateDialog(self.theDlxFileName)
            self.theDialog.AddUpdateHandler(self.update_cb)
            self.theDialog.AddInitializeHandler(self.initialize_cb)
            self.theDialog.AddDialogShownHandler(self.dialogShown_cb)
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            raise ex
        
    
    # ------------------------------- DIALOG LAUNCHING ---------------------------------
    # 
    #     Before invoking this application one needs to open any part/empty part in NX
    #     because of the behavior of the blocks.
    # 
    #     Make sure the dlx file is in one of the following locations:
    #         1.) From where NX session is launched
    #         2.) $UGII_USER_DIR/application
    #         3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    #             recommended. This variable is set to a full directory path to a file 
    #             containing a list of root directories for all custom applications.
    #             e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
    # 
    #     You can create the dialog using one of the following way:
    # 
    #     1. Journal Replay
    # 
    #         1) Replay this file through Tool->Journal->Play Menu.
    # 
    #     2. USER EXIT
    # 
    #         1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    #         2) Invoke the Shared Library through File->Execute->NX Open menu.
    # 
    #------------------------------------------------------------------------------
    
    #------------------------------------------------------------------------------
    # This method shows the dialog on the screen
    #------------------------------------------------------------------------------
    def Show(self):
        try:
            self.theDialog.Show()
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
    
    #------------------------------------------------------------------------------
    # Method Name: Dispose
    #------------------------------------------------------------------------------
    def Dispose(self):
        if self.theDialog != None:
            self.theDialog.Dispose()
            self.theDialog = None
    
    #------------------------------------------------------------------------------
    # ---------------------Block UI Styler Callback Functions--------------------------
    #------------------------------------------------------------------------------
    
    #------------------------------------------------------------------------------
    # Callback Name: initialize_cb
    #------------------------------------------------------------------------------
    def initialize_cb(self):
        try:
            self.group4 = self.theDialog.TopBlock.FindBlock("group4")
            self.label0 = self.theDialog.TopBlock.FindBlock("label0")
            self.selection0 = self.theDialog.TopBlock.FindBlock("selection0")
            self.group = self.theDialog.TopBlock.FindBlock("group")
            self.tree_control0 = self.theDialog.TopBlock.FindBlock("tree_control0")
            self.btn_pending_0 = self.theDialog.TopBlock.FindBlock("btn_pending_0")
            self.btn_pending_recursive = self.theDialog.TopBlock.FindBlock("btn_pending_recursive")
            self.group0 = self.theDialog.TopBlock.FindBlock("group0")
            self.btn_000 = self.theDialog.TopBlock.FindBlock("btn_000")
            self.t_intensity = self.theDialog.TopBlock.FindBlock("t_intensity")
            self.t_X_neg = self.theDialog.TopBlock.FindBlock("t_X_neg")
            self.t_X_pos = self.theDialog.TopBlock.FindBlock("t_X_pos")
            self.t_Y_neg = self.theDialog.TopBlock.FindBlock("t_Y_neg")
            self.t_Y_pos = self.theDialog.TopBlock.FindBlock("t_Y_pos")
            self.t_Z_neg = self.theDialog.TopBlock.FindBlock("t_Z_neg")
            self.t_Z_pos = self.theDialog.TopBlock.FindBlock("t_Z_pos")
            self.group1 = self.theDialog.TopBlock.FindBlock("group1")
            self.listbox_refset = self.theDialog.TopBlock.FindBlock("listbox_refset")
            self.btn_refset_apply = self.theDialog.TopBlock.FindBlock("btn_refset_apply")
            self.group2 = self.theDialog.TopBlock.FindBlock("group2")
            self.btn_fix = self.theDialog.TopBlock.FindBlock("btn_fix")
            self.btn_fix_recursive = self.theDialog.TopBlock.FindBlock("btn_fix_recursive")
            self.group3 = self.theDialog.TopBlock.FindBlock("group3")
            self.btn_freeze = self.theDialog.TopBlock.FindBlock("btn_freeze")
            self.btn_freeze_recursive = self.theDialog.TopBlock.FindBlock("btn_freeze_recursive")
            self.btn_unfreeze = self.theDialog.TopBlock.FindBlock("btn_unfreeze")
            self.btn_unfreeze_recursive = self.theDialog.TopBlock.FindBlock("btn_unfreeze_recursive")
            #------------------------------------------------------------------------------
            # Registration of Treelist specific callbacks
            #------------------------------------------------------------------------------
            # self.tree_control0.SetOnExpandHandler( self.OnExpandCallback )
            
            # self.tree_control0.SetOnInsertColumnHandler( self.OnInsertColumnCallback )
            
            # self.tree_control0.SetOnInsertNodeHandler( self.OnInsertNodeCallback )
            
            # self.tree_control0.SetOnDeleteNodeHandler( self.OnDeleteNodeCallback )
            
            # self.tree_control0.SetOnPreSelectHandler( self.OnPreSelectCallback )
            
            # self.tree_control0.SetOnSelectHandler( self.OnSelectCallback )
            
            # self.tree_control0.SetOnStateChangeHandler( self.OnStateChangeCallback )
            
            # self.tree_control0.SetToolTipTextHandler( self.ToolTipTextCallback )
            
            # self.tree_control0.SetColumnSortHandler( self.ColumnSortCallback )
            
            # self.tree_control0.SetStateIconNameHandler( self.StateIconNameCallback)
            
            # self.tree_control0.SetOnBeginLabelEditHandler( self.OnBeginLabelEdit )
            
            # self.tree_control0.SetOnEndLabelEditHandler( self.OnEndLabelEdit )
            
            # self.tree_control0.SetOnEditOptionSelectedHandler( self.OnEditOptionSelected )
            
            # self.tree_control0.SetAskEditControlHandler( self.AskEditControl )
            
            # self.tree_control0.SetOnMenuHandler(self.OnMenuCallback)
            
            # self.tree_control0.SetOnMenuSelectionHandler(self.OnMenuCommandCallback)
            
            # self.tree_control0.SetIsDropAllowedHandler(self.IsDropAllowedCallback)
            
            # self.tree_control0.SetIsDragAllowedHandler(self.IsDragAllowedCallback)
            
            # self.tree_control0.SetOnDropHandler(self.OnDropCallback)
            
            # self.tree_control0.SetOnDropMenuHandler(self.OnDropMenuCallback)
            
            # self.tree_control0.SetOnDefaultActionHandler(self.OnDefaultActionCallback)
            
            #------------------------------------------------------------------------------
            #------------------------------------------------------------------------------
            # Registration of ListBox specific callbacks
            #------------------------------------------------------------------------------
            # self.listbox_refset.SetAddHandler(self.AddCallback)
            
            # self.listbox_refset.SetDeleteHandler(self.DeleteCallback)
            
            #------------------------------------------------------------------------------
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
    
    #------------------------------------------------------------------------------
    # Callback Name: dialogShown_cb
    # This callback is executed just before the dialog launch. Thus any value set 
    # here will take precedence and dialog will be launched showing that value. 
    #------------------------------------------------------------------------------
    def dialogShown_cb(self):
        try:
            # ---- Enter your callback code here -----
            pass
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
    
    #------------------------------------------------------------------------------
    # Callback Name: update_cb
    #------------------------------------------------------------------------------
    def update_cb(self, block):
        try:
            if block == self.label0:
                # ---- Enter your code here -----
                pass
            elif block == self.selection0:
                # ---- Enter your code here -----
                pass
            elif block == self.btn_pending_0:
                # ---- Enter your code here -----
                pass
            elif block == self.btn_pending_recursive:
                # ---- Enter your code here -----
                pass
            elif block == self.btn_000:
                # ---- Enter your code here -----
                pass
            elif block == self.t_intensity:
                # ---- Enter your code here -----
                pass
            elif block == self.t_X_neg:
                # ---- Enter your code here -----
                pass
            elif block == self.t_X_pos:
                # ---- Enter your code here -----
                pass
            elif block == self.t_Y_neg:
                # ---- Enter your code here -----
                pass
            elif block == self.t_Y_pos:
                # ---- Enter your code here -----
                pass
            elif block == self.t_Z_neg:
                # ---- Enter your code here -----
                pass
            elif block == self.t_Z_pos:
                # ---- Enter your code here -----
                pass
            elif block == self.listbox_refset:
                # ---- Enter your code here -----
                pass
            elif block == self.btn_refset_apply:
                # ---- Enter your code here -----
                pass
            elif block == self.btn_fix:
                # ---- Enter your code here -----
                pass
            elif block == self.btn_fix_recursive:
                # ---- Enter your code here -----
                pass
            elif block == self.btn_freeze:
                # ---- Enter your code here -----
                pass
            elif block == self.btn_freeze_recursive:
                # ---- Enter your code here -----
                pass
            elif block == self.btn_unfreeze:
                # ---- Enter your code here -----
                pass
            elif block == self.btn_unfreeze_recursive:
                # ---- Enter your code here -----
                pass
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
        return 0
    #------------------------------------------------------------------------------
    # Treelist specific callbacks
    #------------------------------------------------------------------------------
    # def OnExpandCallback(self, tree,  node):
    # 
    # 
    
    # def OnInsertColumnCallback(self, tree,  node,  columnID):
    # 
    # 
    
    # def OnInsertNodeCallback(self, tree,  node):
    # 
    # 
    
    # def OnDeleteNodeCallback(self, tree,  node):
    # 
    # 
    
    # def OnPreSelectCallback(self, tree,  node ,  columnID,  selected):
    # 
    # 
    
    # def OnSelectCallback(self, tree,  node ,  columnID,  selected):
    # 
    # 
    
    # def OnStateChangeCallback(self, tree,  node,  State):
    # 
    # 
    
    # def ToolTipTextCallback(self, tree,  node ,  columnID):
    # 
    # 
    
    # def ColumnSortCallback(self, tree,  columnID,  node1,  node2):
    # 
    # 
    
    # def StateIconNameCallback(self, tree,  node,  state):
    # 
    # 
    
    # def OnBeginLabelEdit(self, tree,  node,  columnId):
    # 
    # 
    
    # def OnEndLabelEdit(self, tree,  node,  columnId,  editedText):
    # 
    # 
    
    # def OnEditOptionSelected(self, tree,  node,  columnID,  selectedOptionID,  selectedOptionText,  type):
    # 
    # 
    
    # def AskEditControl(self, tree,  node,  columnID):
    # 
    # 
    
    # def OnMenuCallback(self, tree,  node,  columnID):
    # 
    # 
    
    # def OnMenuCommandCallback(self, tree,  node,  menu_item_id):
    # 
    # 
    
    # def IsDropAllowedCallback(self, tree,  node,  columnID,  targetNode,  targetColumnID):
    # 
    # 
    
    # def IsDragAllowedCallback(self, tree,  node,  columnID):
    # 
    # 
    
    # def OnDropCallback(self, tree,  node,  columnID,  targetNode,  targetColumnID,  dropType,  dropMenuItemId):
    # 
    # 
    
    # def OnDropMenuCallback(self, tree,  node,  columnID,  targetNode,  targetColumnID):
    # 
    # 
    
    # def OnDefaultActionCallback(self, tree,  node,  columnID):
    # 
    # 
    
    #------------------------------------------------------------------------------
    # ListBox specific callbacks
    #------------------------------------------------------------------------------
    # def AddCallback (self list_box):
    # 
    # 
    
    # def DeleteCallback(self, list_box):
    # 
    # 
    
    #------------------------------------------------------------------------------
    
    #------------------------------------------------------------------------------
    # Function Name: GetBlockProperties
    # Returns the propertylist of the specified BlockID
    #------------------------------------------------------------------------------
    def GetBlockProperties(self, blockID):
        try:
            return self.theDialog.GetBlockProperties(blockID)
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
        return None
    
def main():
    thedialog = None
    try:
        thedialog =  dialog()
        #  The following method shows the dialog immediately
        thedialog.Show()
    except Exception as ex:
        # ---- Enter your exception handling code here -----
        NXOpen.UI.GetUI().NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
    finally:
        if thedialog != None:
            thedialog.Dispose()
            thedialog = None
    
if __name__ == '__main__':
    main()

